spring:
  application:
    name: web_shop
  datasource:
    url: jdbc:mysql://localhost:3306/web_shop?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    #password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true

springdoc:
  api-docs:
    path: /api-docs